### ISSUE TITLE
multipart/form-data POST request fails to call servlet

### ISSUE THREAD

**Issue by Rybec** [skeeto/emacs-web-server#13]
This is the curl command that produced the error:
curl --form "fileupload=@ws.el" http://localhost:8080/submit-post

ws.el is just a simple text file I used for testing.

The submit-post servlet is the only thing in its file (test.el).  The first line is supposed to print a message to console, but it never even gets called (I can post the code if it would be useful).

The command line used to start the server is:
emacs -Q -batch -l simple-httpd.el -l test.el -f httpd-batch-start

EDIT: Removed something that was irrelevant.

**Comment by Rybec** [comment]
I believe you were right when you suggested this could be an issue with parsing the header.  I created a small, one line text file to send with the post request, and I added some debugging code to output the `request` variable in `httpd--filter`.  The following is the resulting output, when using the above curl command to send the file:

```
(connection "127.0.0.1")

received content length: 0
content-length: 207
content:
request: ((POST /submit-post HTTP/1.1) (Host localhost:8080) (User-Agent curl/7.52.1) (Accept */*) (Content-Length 207) (Expect 100-continue) (Content-Type multipart/form-data; boundary=------------------------ccc0c7b3ddf9ec70) (Content ))

received content length: 140
content-length: 207
content: --------------------------ccc0c7b3ddf9ec70
Content-Disposition: form-data; name="fileupload"; filename="test.txt"
Content-Type: text/plain
request: ((POST /submit-post HTTP/1.1) (Host localhost:8080) (User-Agent curl/7.52.1) (Accept */*) (Content-Length 207) (Expect 100-continue) (Content-Type multipart/form-data; boundary=------------------------ccc0c7b3ddf9ec70) (--------------------------Ccc0c7b3ddf9ec70 ) (Content-Disposition form-data; name="fileupload"; filename="test.txt") (Content-Type text/plain) (Content --------------------------ccc0c7b3ddf9ec70
Content-Disposition: form-data; name="fileupload"; filename="test.txt"
Content-Type: text/plain))

received content length: 140
content-length: 207
content: --------------------------ccc0c7b3ddf9ec70
Content-Disposition: form-data; name="fileupload"; filename="test.txt"
Content-Type: text/plain
request: ((POST /submit-post HTTP/1.1) (Host localhost:8080) (User-Agent curl/7.52.1) (Accept */*) (Content-Length 207) (Expect 100-continue) (Content-Type multipart/form-data; boundary=------------------------ccc0c7b3ddf9ec70) (--------------------------Ccc0c7b3ddf9ec70 ) (Content-Disposition form-data; name="fileupload"; filename="test.txt") (Content-Type text/plain) (Stuff In A File ) (--------------------------Ccc0c7b3ddf9ec70-- ) (Content --------------------------ccc0c7b3ddf9ec70
Content-Disposition: form-data; name="fileupload"; filename="test.txt"
Content-Type: text/plain))
```

What I am seeing here is that the form data is getting mangled to the point where the `if` statement checking to see if everything has been read cannot get a good number on the length of the incoming form and file data.

I'll look at the code in the parser later.  If I can figure out how to fix it, then I will.  I did mention  that I am just learning elisp though...

**Comment by skeeto** [comment]
That's a perfect example, thanks! The boundary header from the file upload is unusual and was throwing off `httpd-parse`, messing up the content length and causing it to hang on the mismatch.

Rather than attempt to salvage that crappy function I wrote 8 years ago, I rewrote it from scratch (f492baa), doing it correctly this time. It's much more strictly conforming to RFC 2616, and it's *faaaar* more efficient since it plucks header components out a buffer rather than create a bunch of garbage strings.

This also allowed me to fix up `httpd--filter` to concatenate 4kB content chunks into a buffer rather than the dumb string concatenation it had been doing. It also only parses the header once rather than again and again on each 4kB chunk. This will all make things like Skewer work a whole lot better.

Does this fix things on your end?

**Comment by Rybec** [comment]
It looks like it did fix everything!

If you are interested, I spent some time today rewriting the httpd-parse function myself.  It sounds like your solution is significantly better, since it makes httpd--filter handle things better as well, but if you are interested in looking at my code, you can find it in my fork: https://github.com/Rybec/emacs-web-server  (Feel free to comment, if I could have done something better.)

I will probably end up reverting and pulling your changes sometime tomorrow, so it won't be around forever.  I am learning elisp quite quickly as a result of this!
