### ISSUE TITLE
Replacing default servlet

### ISSUE THREAD

**Issue by thblt** [skeeto/emacs-web-server#16]
This is more a request for clarification than an issue: to replace the default/root servlet, one needs to use `defun` to redefine `httpd/`, and the defservlet macros are useless there, am I correct?

Thanks!

**Comment by skeeto** [comment]
While ugly, technically you can use defservlet with the empty symbol:

    (defservlet ## text/plain ()
      (princ "Hello, world!"))

The symbol name is appended to "http/" and interned.

**Comment by thblt** [comment]
I didn't know about the empty symbol, thanks a lot!
